# TensorFlow 2.0 Introduction

In [10]:
!which jupyter

/home/james/anaconda3/envs/learn_tensor/bin/jupyter


## Importing TensorFlow
The first step here is going to be to select the correct version of TensorFlow from within collabratory!


In [1]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook

UsageError: Line magic function `%tensorflow_version` not found.


In [29]:
# Imports
import tensorflow as tf  # now import the tensorflow module
import numpy as np
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/home/james/anaconda3/envs/learn_tensor/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


### Creating Tensors
Below is an example of how to create some different tensors.

You simply define the value of the tensor and the datatype and you are good to go! It's worth mentioning that usually we deal with tensors of numeric data, it is quite rare to see string tensors.

For a full list of datatypes please refer to the following guide.

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [3]:
# using tf.Variable to create different tensors. 
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [5]:
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


###Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar. 

Now we'll 

In [7]:
# creating tensors of higher degrees/ranks. 
rank1_tensor = tf.Variable(["Test"], tf.string) 
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [11]:
# get the shape** of a tensor using the shape attribute.
rank2_tensor.shape

TensorShape([2, 2])


The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [14]:
# Changing Shape of tensor
# tf.ones generates just 1s as elements in the object
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
print(tensor1)                                                                       

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [15]:
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [17]:
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
print(tensor3)
# The numer of elements in the reshaped tensor is always the same

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


###Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```

I've included a few examples that will hopefully help illustrate how we can manipulate tensors with the slice operator.

In [19]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [20]:
tensor

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>

In [21]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3


tf.Tensor(3, shape=(), dtype=int32)


In [22]:
row1 = tensor[0]  # selects the first row
print(row1)




tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [23]:
column1 = tensor[:, 0]  # selects the first column
print(column1)



tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [25]:
row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)


In [26]:
column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor([ 6 11], shape=(2,), dtype=int32)


###Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor




In [34]:
# Constant 1-D Tensor from a python list.
const_tensor = tf.constant([1, 2, 3, 4, 5, 6])
tf.rank(const_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [35]:
# Constant 2-D rom a numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])
const_tensor_2 = tf.constant(arr)
tf.rank(const_tensor_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#Sources
Most of the information is taken direclty from the TensorFlow website which can be found below.

https://www.tensorflow.org/guide/tensor